project 'MedSci Madness.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedSci Madness' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  target 'MedSci MadnessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedSci MadnessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
